"""yes

Revision ID: 59aa92fc270b
Revises: 8642b57352a3
Create Date: 2023-05-01 13:35:53.393047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59aa92fc270b'
down_revision = '8642b57352a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'text_cleaned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('text_cleaned', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
