"""add some columns

Revision ID: 68446fb3e9cb
Revises: 1b5cfc3b358d
Create Date: 2023-05-01 12:44:35.785036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68446fb3e9cb'
down_revision = '1b5cfc3b358d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('cleaned_text', sa.Text(), nullable=True))
    op.add_column('nodes', sa.Column('cleaned_text', sa.Text(), nullable=True))
    op.add_column('nodes', sa.Column('processed_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'processed_text')
    op.drop_column('nodes', 'cleaned_text')
    op.drop_column('documents', 'cleaned_text')
    # ### end Alembic commands ###
