"""yes

Revision ID: 05f684a8e523
Revises: d25544ee41a4
Create Date: 2023-05-02 16:01:53.851610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f684a8e523'
down_revision = 'd25544ee41a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('body_username', sa.String(length=100), nullable=True))
    op.add_column('questions', sa.Column('method', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'method')
    op.drop_column('questions', 'body_username')
    # ### end Alembic commands ###
