"""first_migration_squashed_1

Revision ID: e20c7a892015
Revises: 8eaf24277526
Create Date: 2023-05-09 15:14:18.866218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20c7a892015'
down_revision = '8eaf24277526'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conversations', ['id'])
    op.create_unique_constraint(None, 'documents', ['id'])
    op.create_unique_constraint(None, 'messages', ['id'])
    op.create_unique_constraint(None, 'nodes', ['id'])
    op.create_unique_constraint(None, 'questions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_constraint(None, 'nodes', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_constraint(None, 'conversations', type_='unique')
    # ### end Alembic commands ###
