"""Add text to document

Revision ID: 4f55ebf2e714
Revises: aac8cb4bc9b1
Create Date: 2023-04-28 06:57:30.032792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f55ebf2e714'
down_revision = 'aac8cb4bc9b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'text')
    # ### end Alembic commands ###
