"""Add document title

Revision ID: a29b864e05dc
Revises: 807be8ba48a9
Create Date: 2023-04-23 14:57:25.592029

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a29b864e05dc"
down_revision = "807be8ba48a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("title", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "title")
    # ### end Alembic commands ###
