"""change columns

Revision ID: 8642b57352a3
Revises: 68446fb3e9cb
Create Date: 2023-05-01 13:15:13.325455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8642b57352a3'
down_revision = '68446fb3e9cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('text_no_html', sa.Text(), nullable=True))
    op.drop_column('documents', 'cleaned_text')
    op.add_column('nodes', sa.Column('text_cleaned', sa.Text(), nullable=True))
    op.add_column('nodes', sa.Column('text_processed', sa.Text(), nullable=True))
    op.drop_column('nodes', 'processed_text')
    op.drop_column('nodes', 'cleaned_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('cleaned_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('nodes', sa.Column('processed_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('nodes', 'text_processed')
    op.drop_column('nodes', 'text_cleaned')
    op.add_column('documents', sa.Column('cleaned_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'text_no_html')
    # ### end Alembic commands ###
