"""drop section

Revision ID: b575ed3b4428
Revises: f1db8fda4ef6
Create Date: 2023-04-29 17:16:34.484976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b575ed3b4428'
down_revision = 'f1db8fda4ef6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('document_id', sa.VARCHAR(length=22), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=22), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='sections_document_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sections_pkey'),
    sa.UniqueConstraint('hash', name='sections_hash_key'),
    sa.UniqueConstraint('id', name='sections_id_key')
    )
    # ### end Alembic commands ###
