"""test

Revision ID: a72f99324c9a
Revises: 9da650d96ac7
Create Date: 2023-05-02 13:53:54.115336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72f99324c9a'
down_revision = '9da650d96ac7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=False),
    sa.Column('stripped_query', sa.Text(), nullable=False),
    sa.Column('context_string', sa.Text(), nullable=False),
    sa.Column('first_completion', sa.Text(), nullable=False),
    sa.Column('second_completion', sa.Text(), nullable=False),
    sa.Column('useful_urls_string', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
