"""adadd text length to node

Revision ID: b6f87e46ad81
Revises: b575ed3b4428
Create Date: 2023-04-29 17:31:33.707145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f87e46ad81'
down_revision = 'b575ed3b4428'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('text_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'text_length')
    # ### end Alembic commands ###
