"""add node table

Revision ID: 84b924c0425a
Revises: 4f55ebf2e714
Create Date: 2023-04-28 18:40:23.356061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b924c0425a'
down_revision = '4f55ebf2e714'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nodes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes', type_='unique')
    # ### end Alembic commands ###
