"""Update name from vector to embeddingUpdate the name of vector to embedding

Revision ID: 52274e3fae9b
Revises: 92631b72f0cb
Create Date: 2023-04-26 00:24:05.167394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52274e3fae9b'
down_revision = '92631b72f0cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True))
    op.drop_column('sections', 'vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('vector', postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.drop_column('sections', 'embedding')
    # ### end Alembic commands ###
