"""blah

Revision ID: b38ee4746da9
Revises: a72f99324c9a
Create Date: 2023-05-02 13:56:58.359038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38ee4746da9'
down_revision = 'a72f99324c9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'questions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    # ### end Alembic commands ###
