"""Add vector to sectionAdd vector to section

Revision ID: 92631b72f0cb
Revises: a681b4d28716
Create Date: 2023-04-26 00:21:29.816780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92631b72f0cb'
down_revision = 'a681b4d28716'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('vector', sa.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'vector')
    # ### end Alembic commands ###
