"""add field back

Revision ID: aac8cb4bc9b1
Revises: c79e1c3356ff
Create Date: 2023-04-26 21:59:19.409371

"""
import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aac8cb4bc9b1"
down_revision = "c79e1c3356ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sections",
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sections", "embedding")
    # ### end Alembic commands ###
