"""add external id for documents

Revision ID: f1db8fda4ef6
Revises: e83b2bc7ec94
Create Date: 2023-04-29 15:47:17.270426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1db8fda4ef6'
down_revision = 'e83b2bc7ec94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'documents', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'external_id')
    # ### end Alembic commands ###
