"""drop field

Revision ID: c79e1c3356ff
Revises: f79e09f736a9
Create Date: 2023-04-26 21:50:25.998787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79e1c3356ff'
down_revision = 'f79e09f736a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('embedding', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
