"""Add column

Revision ID: 9da650d96ac7
Revises: 59aa92fc270b
Create Date: 2023-05-01 19:35:20.319905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da650d96ac7'
down_revision = '59aa92fc270b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('text_cleaned', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'text_cleaned')
    # ### end Alembic commands ###
