"""add node hash

Revision ID: 9f342e2d8662
Revises: b6f87e46ad81
Create Date: 2023-04-29 17:33:35.734087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f342e2d8662'
down_revision = 'b6f87e46ad81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'nodes', ['hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes', type_='unique')
    op.drop_column('nodes', 'hash')
    # ### end Alembic commands ###
