"""add field back

Revision ID: f79e09f736a9
Revises: 8a97d576f167
Create Date: 2023-04-26 21:43:27.929801

"""

import sqlalchemy as sa
from sqlalchemy.types import String, TypeDecorator

from alembic import op


class Vector(TypeDecorator):
    impl = String

    def process_bind_param(self, value, dialect):
        if value is not None:
            return ",".join(str(v) for v in value)
        return None

    def process_result_value(self, value, dialect):
        if value is not None:
            return [float(v) for v in value.split(",")]
        return None


# revision identifiers, used by Alembic.
revision = "f79e09f736a9"
down_revision = "8a97d576f167"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sections", sa.Column("embedding", Vector(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sections", "embedding")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
