"""what

Revision ID: 53fc4bb9079e
Revises: cb3f3acb2812
Create Date: 2023-04-29 21:32:46.030737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fc4bb9079e'
down_revision = 'cb3f3acb2812'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nodes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes', type_='unique')
    # ### end Alembic commands ###
