"""Move to document / node setup

Revision ID: e83b2bc7ec94
Revises: 84b924c0425a
Create Date: 2023-04-29 15:04:35.088087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83b2bc7ec94'
down_revision = '84b924c0425a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('document_id', sa.String(length=22), nullable=True))
    op.create_foreign_key(None, 'nodes', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_column('nodes', 'document_id')
    # ### end Alembic commands ###
