"""add hash

Revision ID: 8f6a9cadd494
Revises: 9f342e2d8662
Create Date: 2023-04-29 17:45:46.234987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6a9cadd494'
down_revision = '9f342e2d8662'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('nodes', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('nodes', 'text_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'text_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('nodes', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('nodes', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
