"""add embedding column

Revision ID: 3149013747b3
Revises: 53fc4bb9079e
Create Date: 2023-04-29 21:38:53.846142

"""
import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3149013747b3"
down_revision = "53fc4bb9079e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nodes",
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "embedding")
    # ### end Alembic commands ###
