"""Add hashes to Documents and Sections

Revision ID: a681b4d28716
Revises: a29b864e05dc
Create Date: 2023-04-23 18:50:03.283529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a681b4d28716'
down_revision = 'a29b864e05dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'documents', ['hash'])
    op.add_column('sections', sa.Column('hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'sections', ['hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='unique')
    op.drop_column('sections', 'hash')
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'hash')
    # ### end Alembic commands ###
