"""Adding tag for documents

Revision ID: bdf25407a755
Revises: e20c7a892015
Create Date: 2023-05-09 17:39:04.706303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf25407a755'
down_revision = 'e20c7a892015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('tag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'tag')
    # ### end Alembic commands ###
